const db = [
  {
    id: "1",
    name: "Egyptian Cat",
    images: [
      "CAT0000.png",
      "CAT0001.png",
      "CAT0002.png",
      "CAT0003.png",
      "CAT0004.png",
    ],
    collection: "White x Gold '2019",
    price: "89999",
    details: {
      weight: "4kg",
      dimensions: "1 x 1 x 1 meters",
      useless: "Yes",
      inStock: 4,
    },
  },
  {
    id: "2",
    name: "Flower",
    images: [
      "FLOWER0000.png",
      "FLOWER0001.png",
      "FLOWER0002.png",
      "FLOWER0003.png",
      "FLOWER0004.png",
    ],
    collection: "White x Gold '2019",
    price: "89999",
    details: {
      weight: "4kg",
      dimensions: "1 x 1 x 1 meters",
      useless: "Yes",
      inStock: 3,
    },
  },
  {
    id: "3",
    name: "Jar",
    images: [
      "JAR0000.png",
      "JAR0001.png",
      "JAR0002.png",
      "JAR0003.png",
      "JAR0004.png",
    ],
    collection: "White x Gold '2019",
    price: "89999",
    details: {
      weight: "4kg",
      dimensions: "1 x 1 x 1 meters",
      useless: "Yes",
      inStock: 3,
    },
  },

  {
    id: "4",
    name: "Big Thinker",
    images: [
      "BIGTHINK0000.png",
      "BIGTHINK0001.png",
      "BIGTHINK0002.png",
      "BIGTHINK0003.png",
      "BIGTHINK0004.png",
    ],
    collection: "Sky Blue '2020",
    price: "89999",
    details: {
      weight: "4kg",
      dimensions: "1 x 1 x 1 meters",
      useless: "Yes",
      inStock: 1,
    },
  },
  {
    id: "5",
    name: "Big Bird",
    images: [
      "BIRDIE0000.png",
      "BIRDIE0001.png",
      "BIRDIE0002.png",
      "BIRDIE0003.png",
      "BIRDIE0004.png",
    ],
    collection: "Sky Blue '2020",
    price: "89999",
    details: {
      weight: "4kg",
      dimensions: "1 x 1 x 1 meters",
      useless: "Yes",
      inStock: 0,
    },
  },
  {
    id: "6",
    name: "Ehternal Pillar",
    images: [
      "PILLAR0000.png",
      "PILLAR0001.png",
      "PILLAR0002.png",
      "PILLAR0003.png",
      "PILLAR0004.png",
    ],
    collection: "Sky Blue '2020",
    price: "89999",
    details: {
      weight: "4kg",
      dimensions: "1 x 1 x 1 meters",
      useless: "Yes",
      inStock: 2,
    },
  },
  {
    id: "7",
    name: "Vase Vase",
    images: [
      "VASE0000.png",
      "VASE0001.png",
      "VASE0002.png",
      "VASE0003.png",
      "VASE0004.png",
    ],
    collection: "Sky Blue '2020",
    price: "89999",
    details: {
      weight: "4kg",
      dimensions: "1 x 1 x 1 meters",
      useless: "Yes",
      inStock: 0,
    },
  },
  {
    id: "8",
    name: "Human Hand",
    images: [
      "HAND0000.png",
      "HAND0001.png",
      "HAND0002.png",
      "HAND0003.png",
      "HAND0004.png",
    ],
    collection: "Toxic '2020",
    price: "49999",
    details: {
      weight: "4kg",
      dimensions: "1 x 1 x 1 meters",
      useless: "Yes",
      inStock: 3,
    },
  },
  {
    id: "9",
    name: "Big F",
    images: [
      "FUCK0000.png",
      "FUCK0001.png",
      "FUCK0002.png",
      "FUCK0003.png",
      "FUCK0004.png",
    ],
    collection: "Toxic '2020",
    price: "89999",
    details: {
      weight: "4kg",
      dimensions: "1 x 1 x 1 meters",
      useless: "Yes",
      inStock: 0,
    },
  },
  {
    id: "10",
    name: "Skeleton King",
    images: [
      "SKULL0000.png",
      "SKULL0001.png",
      "SKULL0002.png",
      "SKULL0003.png",
      "SKULL0004.png",
    ],
    collection: "Toxic '2020",
    price: "89999",
    details: {
      weight: "4kg",
      dimensions: "1 x 1 x 1 meters",
      useless: "Yes",
      inStock: 4,
    },
  },
  {
    id: "11",
    name: "Paper Dino",
    images: [
      "DINO0000.png",
      "DINO0001.png",
      "DINO0002.png",
      "DINO0003.png",
      "DINO0004.png",
    ],
    collection: "Vulcanic '2021",
    price: "89999",
    details: {
      weight: "4kg",
      dimensions: "1 x 1 x 1 meters",
      useless: "Yes",
      inStock: 6,
    },
  },
  {
    id: "12",
    name: "Holding Hands",
    images: [
      "COUPLEHANDS0000.png",
      "COUPLEHANDS0001.png",
      "COUPLEHANDS0002.png",
      "COUPLEHANDS0003.png",
      "COUPLEHANDS0004.png",
    ],
    collection: "Vulcanic '2021",
    price: "89999",
    details: {
      weight: "4kg",
      dimensions: "1 x 1 x 1 meters",
      useless: "Yes",
      inStock: 7,
    },
  },
  {
    id: "13",
    name: "Cube Assembly",
    images: [
      "CUBES0000.png",
      "CUBES0001.png",
      "CUBES0002.png",
      "CUBES0003.png",
      "CUBES0004.png",
    ],
    collection: "Vulcanic '2021",
    price: "89999",
    details: {
      weight: "4kg",
      dimensions: "1 x 1 x 1 meters",
      useless: "Yes",
      inStock: 5,
    },
  },
  {
    id: "14",
    name: "Chinese Dragon",
    images: [
      "DRAGON0000.png",
      "DRAGON0001.png",
      "DRAGON0002.png",
      "DRAGON0003.png",
      "DRAGON0004.png",
    ],
    collection: "Vulcanic '2021",
    price: "89999",
    details: {
      weight: "4kg",
      dimensions: "1 x 1 x 1 meters",
      useless: "Yes",
      inStock: 2,
    },
  },
  {
    id: "15",
    name: "Human Heart",
    images: [
      "HEART0000.png",
      "HEART0001.png",
      "HEART0002.png",
      "HEART0003.png",
      "HEART0004.png",
    ],
    collection: "Vulcanic '2021",
    price: "89999",
    details: {
      weight: "4kg",
      dimensions: "1 x 1 x 1 meters",
      useless: "Yes",
      inStock: 4,
    },
  },
];

module.exports = db;
